name: Django CI/CD with Docker

on:
  push:
    branches:
      - master
      # - stage
      - production
    tags:
      - 'v*'

  pull_request:
    branches:
      - master
      # - stage
      - production


jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    env:
      DB_NAME: test_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: core.settings

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python manage.py migrate

      - name: Run pytest
        run: pytest


  docker_build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------------- DEV ----------------
      - name: Build and push dev (master)
        if: github.ref == 'refs/heads/master'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:dev

      # # ---------------- STAGING ----------------
      # - name: Build and push staging
      #   if: github.ref == 'refs/heads/stage'
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:staging .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:staging

      # ---------------- PRODUCTION ----------------
      - name: Build and push production
        # if: github.ref == 'refs/heads/production'
        run: |

          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:latest
  # deploy:
  #   runs-on: self-hosted
  #   needs: docker_build

  #   steps:
  #     - name: Deploy latest container
  #       run: |
  #         docker pull ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:latest

  #         docker stop inventory || true
  #         docker rm inventory || true

  #         # 1. run initialization FIRST
  #         docker run --rm \
  #           --env-file /home/vuth/inventory/.env \
  #           -v /home/vuth/inventory/media:/app/media \
  #           -v /home/vuth/inventory/qdrant_storage:/app/qdrant_storage \
  #           ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:latest \
  #           python manage.py initialize_image_search

  #         # 2. then start server
  #         docker run -d \
  #           --name inventory \
  #           -p 8000:8000 \
  #           --env-file /home/vuth/inventory/.env \
  #           -v /home/vuth/inventory/media:/app/media \
  #           -v /home/vuth/inventory/qdrant_storage:/app/qdrant_storage \
  #           ${{ secrets.DOCKER_USERNAME }}/django-inventory-mobile:latest